POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "sorana@yahoo.com",
  "password": "sorana"
}

###

### GET Request to /api/plants with JWT Token
GET http://localhost:8080/api/plants
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzb3JhbmFAeWFob28uY29tIiwibGFzdE5hbWUiOiJYIiwiaWF0IjoxNzA0MzY4NDMzLCJleHAiOjE3MDQ2Mjc2MzN9.Cx12lKaPeSyQuJ4aSBSnKURx_iUHl8VCokr322nhz_flc-hapXAtuRnEVs-dlR0S-wun4k3NBn0ZSkkaO5HSDA

###
